### ISSUE TITLE
Chrome: Flickering/current items not directly sliding away

### ISSUE THREAD

**Issue by Stryker93** [tutorialdrive/Bootstrap-3-Vertical-Thumbnail-Carousel#1]
In the current version of chrome (V 37) the current items are not sliding away, when the new items are sliding. So the new items slide over the current items and the current items only slide away after the new items are on position. This looks very strange and seems like that they are flickering.

In current Firefox und Safari it works as expected.

**Comment by novaq** [comment]
+1

**Comment by tutorialdrive** [comment]
Issue Solved. Please review at Fix Bug "Image Overlapping and Flickering" in CSS
Issue is that carousel container (#myCarousel) doesn't have an explicit height. Its child .carousel-inner has height:100%, but since #myCarousel doesn't have explicit height, this percentage value has no effect, as do %-based offsets of carousel items.
