### ISSUE TITLE
IE 11 and Chrome v42

### ISSUE THREAD

**Issue by darkarchon** [tutorialdrive/Bootstrap-3-Vertical-Thumbnail-Carousel#3]
## Doesn't work properly
Sliding effect is broken

**Comment by tutorialdrive** [comment]
Issue Solved. Please review at Fix Bug "Image Overlapping and Flickering" in CSS
Issue is that carousel container (#myCarousel) doesn't have an explicit height. Its child .carousel-inner has height:100%, but since #myCarousel doesn't have explicit height, this percentage value has no effect, as do %-based offsets of carousel items.
